completed assessment
learn-academy-2022-charlie/week-1-assessment-jjames177 pull request #1
Opened 2022-05-16 17:05 UTC by jjames177

# Submitting Week 1 Assessment

### ✅ Completed Files
Select the following as confirmation that the files in this repository are complete.
- [ ] Coding Challenges
- [x ] Coding Concepts
- [x ] Interview Questions

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here: i did not finish the coding challenges, life really happened this weekend.

2022-05-16 18:14 UTC, WalkerTexas-coder requested changes
Looks like we are missing all three files! Add, commit and push them up to this branch for review!

2022-05-18 16:27 UTC, WalkerTexas-coder approved these changes
James you did a great job on this assessment! Keep up the good work into the next assessment. If you want, feel free to come up with multiple solutions to the code problems using different tool sets and document that process. Great work! Approved.

2022-05-18 16:27 UTC, WalkerTexas-coder commented on code-challenges.js
> +console.log(boilingPoint(temp3)) //Output = 212, is at boiling point
Nicely done!

2022-05-18 16:27 UTC, WalkerTexas-coder commented on code-challenges.js
> +console.log(splitLetters.join('')) // Output = 2202 eilrahC
Good stuff. You are welcome to use variables that are given to you too.

2022-05-18 16:27 UTC, WalkerTexas-coder commented on code-challenges.js
> +console.log(smallerNumbers(number3, number4)) // Output = 3
Very cool

2022-05-18 16:27 UTC, WalkerTexas-coder commented on coding-concepts.js
> +
Thanks for sharing the error code! Yea this one is tricksy on purpose. The goal here is that we recognize methods only work on certain data types that they are associated with.

2022-05-18 16:27 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Researched answer: Git is the tool that i mentioned in my answer that can have an unlimited amount of versions of code. GitHub is mainly used for sending repositories and updating them constantly,
Excellent! Yea, Git is a software that is installed on computers like any application.

2022-05-18 16:27 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Researched answer: I learned that iterations are used in many computer languages and programs to perform important and specific task, complete problem solving, and when the iteration is complete it
Nicely done!

2022-05-19 00:03 UTC, jjames177 commented on interview-questions.md
> +  Researched answer: I learned that iterations are used in many computer languages and programs to perform important and specific task, complete problem solving, and when the iteration is complete it
Thanks Austin!

2022-05-19 00:03 UTC, merged